# Generated by Django 5.2.1 on 2025-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(default='v1.0', max_length=50)),
                ('apk_file', models.FileField(upload_to='apks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CEO', 'Chief Executive Officer'), ('CTO', 'Chief Technical Officer'), ('CFO', 'Chief Financial Officer')], max_length=3, unique=True)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team_photos/')),
            ],
        ),
    ]
